src/Rs/CollezioneStronatiBundle/Entity/Foto.php
<?php

namespace Rs\CollezioneStronatiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Exclude;


/**
 * Foto
 *
 * @ORM\Table(name="foto")
 * @ORM\Entity
 */
class Foto
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="tmp_name", type="string", length=255)
     */
    private $nome;

    /**
     * @var string
     *
     * @ORM\Column(name="mime", type="string", length=50)
     */
    private $mime;

    /**
     * @var integer
     *
     * @ORM\Column(name="dimensioni", type="integer")
     */
    private $dimensioni;

    /**
     * @var string
     *
     * @ORM\Column(name="tipo", type="string", length=255, nullable=true)
     */
    private $tipo;

    /**
     * @var string
     *
     * @ORM\Column(name="contenuto", type="blob")
     */
    private $contenuto;

    /**
     * @ORM\ManyToOne(targetEntity="Oggetto", inversedBy="foto")
     * @ORM\JoinColumn(name="oggetto_id", referencedColumnName="id", nullable = true)
     * @Exclude
     * */
    private $oggetto;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    public function setId($id){
        $this->id = $id;
    }

    /**
     * Set mime
     *
     * @param string $mime
     * @return Foto
     */
    public function setMime($mime)
    {
        $this->mime = $mime;

        return $this;
    }

    /**
     * Get mime
     *
     * @return string 
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * Set dimensioni
     *
     * @param integer $dimensioni
     * @return Foto
     */
    public function setDimensioni($dimensioni)
    {
        $this->dimensioni = $dimensioni;

        return $this;
    }

    /**
     * Get dimensioni
     *
     * @return integer 
     */
    public function getDimensioni()
    {
        return $this->dimensioni;
    }

    /**
     * Set tipo
     *
     * @param string $tipo
     * @return Foto
     */
    public function setTipo($tipo)
    {
        $this->tipo = $tipo;

        return $this;
    }

    /**
     * Get tipo
     *
     * @return string 
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * Set contenuto
     *
     * @param string $contenuto
     * @return Foto
     */
    public function setContenuto($contenuto)
    {
        $this->contenuto = $contenuto;

        return $this;
    }

    /**
     * Get contenuto
     *
     * @return string 
     */
    public function getContenuto()
    {
        return $this->contenuto;
    }

    /**
     * @param mixed $oggetto
     */
    public function setOggetto($oggetto)
    {
        $this->oggetto = $oggetto;
    }

    /**
     * @return mixed
     */
    public function getOggetto()
    {
        return $this->oggetto;
    }

    /**
     * @param string $nome
     */
    public function setNome($nome)
    {
        $this->nome = $nome;
    }

    /**
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }


    public function getStream(){
        return \base64_encode(stream_get_contents($this->contenuto));
    }
}

src/Rs/CollezioneStronatiBundle/Controller/OggettiController.php
<?php

namespace Rs\CollezioneStronatiBundle\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use Rs\CollezioneStronatiBundle\Entity\Bicchiere;
use Rs\CollezioneStronatiBundle\Entity\Profumo;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Rs\CollezioneStronatiBundle\Entity\Mignon;
use Rs\CollezioneStronatiBundle\Entity\Produttore;
use Rs\CollezioneStronatiBundle\Form\ProduttoreType;



class OggettiController extends CollezioneStronatiController
{
    /**
     * Lists all Mignon entities.
     *
     * @Route("/carica", name="pagina_caricamento")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        return array();
    }

    /**
     * Lists all Mignon entities.
     *
     * @Route("/", name="mostra_immagini")
     * @Method("GET")
     * @Template()
     */
    public function mostraImmaginiAction()
    {
        $uploadManager = $this->get('rs.collezionestronati.foto.upload');
        $response =$uploadManager->get();
        return $response;
    }

    /**
     * @Route("/", name="caricamento_immagini")
     * @Method("POST")
     */
    public function caricamentoImmaginiAction(Request $request)
    {
        $uploadManager = $this->get('rs.collezionestronati.foto.upload');
        $response =$uploadManager->post();
        return $response;
    }

    /**
     * @Route("/", name="cancella_immagini")
     * @Method("DELETE")
     */
    public function cancellaImmaginiAction(Request $request)
    {
        $uploadManager = $this->get('rs.collezionestronati.foto.upload');
        $response =$uploadManager->delete();
        return $response;
    }

    /**
     * @Route("/mostra/{id}", name="mostra_immagine")
     * @Method("GET")
     */
    public function mostraFotoAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('RsCollezioneStronatiBundle:Foto');

        $foto = $repository->find($id);


        $response = new StreamedResponse(
            function () use ($foto) {
                echo stream_get_contents($foto->getContenuto());
            });
        $response->headers->set('Content-Type', 'image/jpeg');
        $response->headers->set('Content-Disposition', 'inline;filename='.$foto->getNome());
        return $response;

        /*
        $response = $this->getResponse();
        $response->clearHttpHeaders();
        $response->setContentType ($this->image->getMimeType());
        $response->setHttpHeader ('Content-Disposition', 'inline;filename='.$foto->getNome());
        $content = $foto->getContenuto();
        $response->setContent (stream_get_contents ($content));

        $this->setLayout (false);
        return sfView::NONE;
        */
    }


    /**
     * @Route("/cataloga", name="cataloga_immagini")
     * @Method("GET")
     * @Template()
     */
    public function catalogaImmaginiAction()
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('RsCollezioneStronatiBundle:Foto');

        $foto = $repository->findBy(array("oggetto"=>null), array('nome'=> 'ASC'));

        return array("listaFoto" => $foto);
    }

    /**
     * @Route("/cataloga", name="cataloga_immagine")
     * @Method("POST")
     * @Template()
     */
    public function catalogaImmagineAction(Request $request)
    {

        $mignon = new Mignon();
        $profumo = new Profumo();
        $bicchiere = new Bicchiere();

        $em = $this->getDoctrine()->getManager();

        $repositoryFoto = $em->getRepository('RsCollezioneStronatiBundle:Foto');
        $fotoArray = new ArrayCollection();
        foreach($request->get('fotoSelezionate') as $idFoto){
            $foto = $repositoryFoto->find($idFoto);
            if($foto != null){
                $fotoArray->add($foto);
            }
        }

        if( $fotoArray->count() > 0 ){
            $mignon->setFoto($fotoArray);
            $profumo->setFoto($fotoArray);
            $bicchiere->setFoto($fotoArray);
        }


        if($request->request->get("idProduttore") != null){
            $produttore = $em->getRepository('RsCollezioneStronatiBundle:Produttore')->find($request->request->get("idProduttore"));
            if($produttore!=null){
                $mignon->setProduttore($produttore);
                $profumo->setProduttore($produttore);
                $bicchiere->setProduttore($produttore);
            }

        }

        $formBuilder = $this->get('rs.collezionestronati.form.builder');
        $formMignon = $formBuilder->generaNuovoOggettoForm('Rs\CollezioneStronatiBundle\Form\BaseType\MignonType',
            $mignon,
            'mignon_create');

        $formBicchiere = $formBuilder->generaNuovoOggettoForm('Rs\CollezioneStronatiBundle\Form\BaseType\BicchiereType',
            $bicchiere,
            'bicchiere_create');

        $formProfumo = $formBuilder->generaNuovoOggettoForm('Rs\CollezioneStronatiBundle\Form\BaseType\ProfumoType',
            $profumo,
            'profumo_create');

        $formProduttore = $this->createForm(new ProduttoreType(), new Produttore(), array(
            'action' => $this->generateUrl('produttore_create'),
            'method' => 'POST',
        ));

        return array("formMignon" => $formMignon->createView(),
            "formProfumo" => $formProfumo->createView(),
            "formBicchiere" => $formBicchiere->createView(),
            "formProduttore" => $formProduttore->createView()
        );

    }

    /**
     * @Route("/genera_form/{tipo}", name="genera_form")
     * @Method("GET")
     */
    public function generaFormAction(Request $request,$tipo){

    }
}

src/Rs/CollezioneStronatiBundle/Resources/views/Oggetti/catalogaImmagine.html.twig
{% extends 'RsCollezioneStronatiBundle::unaColonna.html.twig' %}
{% set nomePagina = 'Immagini da catalogare'  %}

{% block stylesheets %}
    <link  href="{{asset("bundles/collezionestronati/css/select2.css")}}" rel="stylesheet" type="text/css" />
    <link  href="{{asset("bundles/collezionestronati/css/select2-bootstrap.css")}}" rel="stylesheet" type="text/css" />

{% endblock %}

{% block contenuto -%}
    <div class="row">
        <div class="col-lg-4">
        {% for foto in formMignon.vars.value.foto %}
            <div class="box box-solid bg-gray" id="foto-{{ foto.id }}">
                <div class="box-header">
                    <h3 class="box-title">
                        {{ foto.nome }}
                    </h3>
                </div>
                <div class="box-body">
                    <img src="data:image/jpeg;base64,{{ foto.stream }}" />
                </div>
            </div>
            <br>
            <br>
        {% endfor %}
        </div>
        <div class="col-lg-8">
            <h3>Tipo Oggetto</h3>
            <select id="tipo_oggetto">
                <option></option>
                <option value="mignon">Mignon</option>
                <option value="bicchiere">Bicchiere</option>
                <option value="profumo">Profumo</option>
            </select>
            <br><br><br>
            <div id="form_mignon">
                <h3>Mignon</h3>
                {{ form(formMignon) }}
            </div>
            <br>
            <div id="form_bicchiere">
                <h3>Bicchiere</h3>
                {{ form(formBicchiere) }}
            </div>
            <br>
            <div id="form_profumo">
                <h3>Profumo</h3>
                {{ form(formProfumo) }}
            </div>
            <br>
            <div id="modal_produttore" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Inserimento di un nuovo produttore</h4>
                        </div>
                        <div class="modal-body">
                            {{ form_start(formProduttore) }}
                            {{ form_errors(formProduttore) }}

                            {{ form_row(formProduttore.nome) }}
                            {{ form_row(formProduttore.dataFondazione) }}
                            {{ form_row(formProduttore.dataChiusura) }}
                            {{ form_row(formProduttore.indirizzo) }}

                            {% for foto in formMignon.vars.value.foto %}
                                <input type="hidden" name="fotoSelezionate[]" value="{{ foto.id }}">
                            {% endfor %}
                            {{ form_widget(formProduttore._token) }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
                            <button type="button" class="btn btn-primary" id="salva_produttore">Salva</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{asset("bundles/collezionestronati/js/select2.min.js")}}" type="text/javascript"></script>


    <script type="text/javascript">
        $(function() {
            $("div[id^='form_']").each(function(){
                $(this).hide();
            });

            $('#rs_collezionestronatibundle_mignon_produttore').after('<br><br><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modal_produttore">Nuovo produttore</a><br><br>');
            $('#rs_collezionestronatibundle_bicchiere_produttore').after('<br><br><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modal_produttore">Nuovo produttore</a><br><br>');
            $('#rs_collezionestronatibundle_profumo_produttore').after('<br><br><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modal_produttore">Nuovo produttore</a><br><br>');
        });

        $("#tipo_oggetto").change(function(){
            $("div[id^='form_']").each(function(){
                $(this).hide();
            });
            var select = $(this).val();
            $("#form_"+select).show();
        });

        $("#salva_produttore").click(function(){
            $('form[name="rs_collezionestronatibundle_produttore"]').submit();
        })

        $("#rs_collezionestronatibundle_mignon_produttore").select2({
            placeholder: "Selezionare un produttore",
            allowClear: true,
            width: 'resolve'
        });

        $("#rs_collezionestronatibundle_bicchiere_produttore").select2({
            placeholder: "Selezionare un produttore",
            allowClear: true,
            width: 'resolve'
        });

        $("#rs_collezionestronatibundle_profumo_produttore").select2({
            placeholder: "Selezionare un produttore",
            allowClear: true,
            width: 'resolve'
        });

        $("#tipo_oggetto").select2({
            placeholder: "Selezionare un tipo di oggetto",
            allowClear: true,
            width: 'resolve'
        });

    </script>
{% endblock %}

src/Rs/CollezioneStronatiBundle/Resources/views/Oggetti/catalogaImmagini.html.twig
{% extends 'RsCollezioneStronatiBundle::unaColonna.html.twig' %}
{% set nomePagina = 'Elenco immagini da catalogare'  %}

{% block contenuto -%}
        <!-- The file upload form used as target for the file upload widget -->
            {% if listaFoto|length  %}
                <form id="fileupload" action="{{ path('cataloga_immagine') }}" method="POST">

                {% set fotoPerColonna = 4 %}

                {% for foto in listaFoto %}

                    {% if loop.index0 % fotoPerColonna == 0 or loop.first %}
                        <div class="row">
                    {% endif %}

                    <div class="col-md-3">
                        <div class="box box-solid bg-gray" id="foto-{{ foto.id }}">
                            <div class="box-header">
                                <h3 class="box-title">
                                    {{ foto.nome }}
                                </h3>
                            </div>
                            <div class="box-body">
                                <img src="data:image/jpeg;base64,{{ foto.stream }}" />
                            </div>
                        </div>
                    </div>

                    {% if loop.index % fotoPerColonna == 0 or loop.last %}
                        </div>
                    {% endif %}

                {% endfor %}
                <br>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="submit" value="Cataloga" class="btn btn-primary">
                    </div>
                </div>

                </form>
            {% else %}
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-1">
                        <div class="alert alert-info">
                            <button data-dismiss="alert" class="close" type="button">×</button>
                            Nessun elemento nuovo da catalogare
                        </div>
                    </div>
                </div>
            {% endif %}

        <br>
{% endblock %}

{% block javascripts %}
<script type="text/javascript">

    $("div[id^='foto-']").click(function(){
        $(this).toggleClass("bg-red");
        var idElemento = $(this).prop("id");
        var idFoto = idElemento.split("-");
        idFoto = idFoto[1];
        if($("#fotoselezionata-"+idFoto).length ){
            $("#fotoselezionata-"+idFoto).remove();
        }else{
            var input = $('<input>').attr({
                type: 'hidden',
                id: "fotoselezionata-"+idFoto,
                name: 'fotoSelezionate[]',
                value: idFoto
            });
            $('#fileupload').append(input);
        }
    })
</script>
{% endblock %}

src/Rs/CollezioneStronatiBundle/Resources/views/Oggetti/index.html.twig
{% extends '::base.html.twig' %}
{% set nomePagina = 'Carica nuove immagini'  %}

{% block stylesheets %}
    <!-- Generic page styles -->
    <link rel="stylesheet" href="{{ asset('bundles/collezionestronati/css/style.css')}}">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="{{ asset('bundles/collezionestronati/css/jquery.fileupload.css')}}">
    <link rel="stylesheet" href="{{ asset('bundles/collezionestronati/css/jquery.fileupload.css')}}">
    <link rel="stylesheet" href="{{ asset('bundles/collezionestronati/css/jquery.fileupload-ui.css')}}">
    <!-- CSS adjustments for browsers with JavaScript disabled -->
    <noscript><link rel="stylesheet" href="{{ asset('bundles/collezionestronati/css/jquery.fileupload-noscript.css')}}"></noscript>
    <noscript><link rel="stylesheet" href="{{ asset('bundles/collezionestronati/css/jquery.fileupload-ui-noscript.css')}}"></noscript>
{% endblock %}
{% block container -%}
    <div class="container">
        <!-- The file upload form used as target for the file upload widget -->
        <form id="fileupload" action="{{ path('caricamento_immagini') }}" method="POST" enctype="multipart/form-data">
            <!-- Redirect browsers with JavaScript disabled to the origin page -->
            <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="row fileupload-buttonbar">
                <div class="col-lg-7">
                    <!-- The fileinput-button span is used to style the file input field as button -->
                    <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                    </span>
                    <button type="submit" class="btn btn-primary start">
                        <i class="glyphicon glyphicon-upload"></i>
                        <span>Start upload</span>
                    </button>
                    <button type="reset" class="btn btn-warning cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Cancel upload</span>
                    </button>
                    <button type="button" class="btn btn-danger delete">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Delete</span>
                    </button>
                    <input type="checkbox" class="toggle">
                    <!-- The global file processing state -->
                    <span class="fileupload-process"></span>
                </div>
                <!-- The global progress state -->
                <div class="col-lg-5 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                    <!-- The extended global progress state -->
                    <div class="progress-extended">&nbsp;</div>
                </div>
            </div>
            <!-- The table listing the files available for upload/download -->
            <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
        </form>
        <br>
    </div>
    <!-- The blueimp Gallery widget -->
    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% verbatim %}
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
<tr class="template-upload fade">
<td>
<span class="preview"></span>
</td>
<td>
<p class="name">{%=file.name%}</p>
<strong class="error text-danger"></strong>
</td>
<td>
<p class="size">Processing...</p>
<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
</td>
<td>
{% if (!i && !o.options.autoUpload) { %}
<button class="btn btn-primary start" disabled>
<i class="glyphicon glyphicon-upload"></i>
<span>Start</span>
</button>
{% } %}
{% if (!i) { %}
<button class="btn btn-warning cancel">
<i class="glyphicon glyphicon-ban-circle"></i>
<span>Cancel</span>
</button>
{% } %}
</td>
</tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
<tr class="template-download fade">
<td>
<span class="preview">
{% if (file.thumbnailUrl) { %}
<a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
{% } %}
</span>
</td>
<td>
<p class="name">
{% if (file.url) { %}
<a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
{% } else { %}
<span>{%=file.name%}</span>
{% } %}
</p>
{% if (file.error) { %}
<div><span class="label label-danger">Error</span> {%=file.error%}</div>
{% } %}
</td>
<td>
<span class="size">{%=o.formatFileSize(file.size)%}</span>
</td>
<td>
{% if (file.deleteUrl) { %}
<button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
<i class="glyphicon glyphicon-trash"></i>
<span>Delete</span>
</button>
<input type="checkbox" name="delete" value="1" class="toggle">
{% } else { %}
<button class="btn btn-warning cancel">
<i class="glyphicon glyphicon-ban-circle"></i>
<span>Cancel</span>
</button>
{% } %}
</td>
</tr>
{% } %}
</script>
{% endverbatim %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
    <script src="{{ asset('bundles/collezionestronati/js/vendor/jquery.ui.widget.js')}}"></script>
    <!-- The Templates plugin is included to render the upload/download listings -->
    <script src="http://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
    <!-- blueimp Gallery script -->
    <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
    <script src="{{ asset('bundles/collezionestronati/js/jquery.iframe-transport.js')}}"></script>
    <!-- The basic File Upload plugin -->
    <script src="{{ asset('bundles/collezionestronati/js/jquery.fileupload.js')}}"></script>
    <!-- The File Upload processing plugin -->
    <script src="{{ asset('bundles/collezionestronati/js/jquery.fileupload-process.js')}}"></script>
    <!-- The File Upload image preview & resize plugin -->
    <script src="{{ asset('bundles/collezionestronati/js/jquery.fileupload-image.js')}}"></script>
    <!-- The File Upload validation plugin -->
    <script src="{{ asset('bundles/collezionestronati/js/jquery.fileupload-validate.js')}}"></script>
    <!-- The File Upload user interface plugin -->
    <script src="{{ asset('bundles/collezionestronati/js/jquery.fileupload-ui.js')}}"></script>
    <!-- The main application script -->
    <script type="text/javascript">
        $(function () {
            'use strict';
            // Initialize the jQuery File Upload widget:
            $('#fileupload').fileupload({
                // Uncomment the following to send cross-domain cookies:
                //xhrFields: {withCredentials: true},
                url: '{{ path('caricamento_immagini') }}',
                disableImageResize: /Android(?!.*Chrome)|Opera/
                        .test(window.navigator && navigator.userAgent),
                imageMaxWidth: 800,
                imageMaxHeight: 800,
                imageCrop: false // Force cropped images
            });

            // Enable iframe cross-domain access via redirect option:
            $('#fileupload').fileupload(
                    'option',
                    'redirect',
                    window.location.href.replace(
                            /\/[^\/]*$/,
                            '/cors/result.html?%s'
                    )
            );

            // Load existing files:
            $('#fileupload').addClass('fileupload-processing');
            $.ajax({
                // Uncomment the following to send cross-domain cookies:
                //xhrFields: {withCredentials: true},
                url: $('#fileupload').fileupload('option', 'url'),
                dataType: 'json',
                context: $('#fileupload')[0]
            }).always(function () {
                        $(this).removeClass('fileupload-processing');
                    }).done(function (result) {
                        $(this).fileupload('option', 'done')
                                .call(this, $.Event('done'), {result: result});
                    });

        });
    </script>
{% endblock %}